### ISSUE TITLE
Update Build Instructions

### ISSUE THREAD

**Issue by DavidRChristensen** [tgraf/bmon#22]
Dependencies:
- On Ubuntu 14.04 Desktop I also needed to run "apt-get install libncurses-dev" in order for "./configure" to complete successfully.

Installation:
- No mention of running "./autogen.sh" before attempting to run "./configure".

**Comment by tgraf** [comment]
Fixed in commit c1ae292c9542c52f50ab1daf7394cec49960403c and 2a410be36f5380e5d986dd3bccf20466d3b5930b.  Thanks for reporting this issue.
