### ISSUE TITLE
bmon 3.6 on OSX 10.10.3

### ISSUE THREAD

**Issue by hdatma** [tgraf/bmon#27]
Dear Thomas, 

Please find enclosed the logs obtained compiling bmon on OSX 10.10.3. 

Yours sincerely,

## Notes:

https://github.com/tgraf/bmon/releases/download/v3.6/bmon-3.6.tar.gz

> clang -v
clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

### configure stdout:

checking build system type... x86_64-apple-darwin14.3.0
checking host system type... x86_64-apple-darwin14.3.0
checking target system type... x86_64-apple-darwin14.3.0
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... /opt/llvm/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/llvm/bin/clang accepts -g... yes
checking for /opt/llvm/bin/clang option to accept ISO C89... none needed
checking dependency style of /opt/llvm/bin/clang... gcc3
checking for library containing strerror... none required
checking for gcc... (cached) /opt/llvm/bin/clang
checking whether we are using the GNU C compiler... (cached) yes
checking whether /opt/llvm/bin/clang accepts -g... (cached) yes
checking for /opt/llvm/bin/clang option to accept ISO C89... (cached) none needed
checking dependency style of /opt/llvm/bin/clang... (cached) gcc3
checking for /opt/llvm/bin/clang option to accept ISO C99... none needed
checking for /opt/llvm/bin/clang option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... /opt/llvm/bin/clang -E
checking whether make sets $(MAKE)... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether time.h and sys/time.h may both be included... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking return type of signal handlers... void
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking ncurses/ncurses.h usability... no
checking ncurses/ncurses.h presence... no
checking for ncurses/ncurses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking sys/sockio.h usability... yes
checking sys/sockio.h presence... yes
checking for sys/sockio.h... yes
checking netinet6/in6.h usability... no
checking netinet6/in6.h presence... no
checking for netinet6/in6.h... no
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sysctl/ioctl.h usability... no
checking sysctl/ioctl.h presence... no
checking for sysctl/ioctl.h... no
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for suseconds_t... yes
checking for atexit... yes
checking for gettimeofday... yes
checking for memset... yes
checking for pow... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strstr... yes
checking for strtol... yes
checking for uname... yes
checking for getdate... yes
checking for NcursesW wide-character library... no
checking for Ncurses library... yes
checking for working ncurses/curses.h... no
checking for working ncurses.h... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CONFUSE... yes
checking for pow in -lm... yes
checking for initscr in -lncurses... yes
checking for redrawwin in -lncurses... yes
checking for use_default_colors in -lncurses... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating examples/Makefile
config.status: creating include/bmon/defs.h
config.status: executing depfiles commands
 
### configure stderr:

empty

### compiler's stdout:

Making all in src
  CC       bmon-utils.o
  CC       bmon-unit.o
  CC       bmon-conf.o
  CC       bmon-input.o
  CC       bmon-output.o
  CC       bmon-group.o
  CC       bmon-element.o
  CC       bmon-attr.o
  CC       bmon-element_cfg.o
  CC       bmon-history.o
  CC       bmon-graph.o
  CC       bmon-bmon.o
  CC       bmon-module.o
  CC       bmon-in_netlink.o
  CC       bmon-in_null.o
  CC       bmon-in_dummy.o
  CC       bmon-in_proc.o
  CC       bmon-in_sysctl.o
  CC       bmon-out_null.o
  CC       bmon-out_format.o
  CC       bmon-out_ascii.o
  CC       bmon-out_curses.o
  CCLD     bmon
 
### compiler's stderr:

Undefined symbols for architecture x86_64:
  "_cfg_free", referenced from:
      _conf_shutdown in bmon-conf.o
     (maybe you meant: _element_cfg_free)
  "_cfg_getbool", referenced from:
      _unit_divisor in bmon-unit.o
      _conf_init_post in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_getfloat", referenced from:
      _conf_init_post in bmon-conf.o
      _get_lifecycles in bmon-conf.o
      _configfile_read_history in bmon-conf.o
  "_cfg_getint", referenced from:
      _conf_init_post in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
      _main in bmon-bmon.o
  "_cfg_getnfloat", referenced from:
      _add_div in bmon-conf.o
  "_cfg_getnsec", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_getnstr", referenced from:
      _add_div in bmon-conf.o
  "_cfg_getstr", referenced from:
      _conf_init_post in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_init", referenced from:
      ___conf_init in bmon-conf.o
  "_cfg_parse", referenced from:
      _conf_read in bmon-conf.o
  "_cfg_parse_buf", referenced from:
      _conf_init_pre in bmon-conf.o
  "_cfg_setbool", referenced from:
      _main in bmon-bmon.o
  "_cfg_setfloat", referenced from:
      _main in bmon-bmon.o
  "_cfg_setint", referenced from:
      _set_unit_exp in bmon-conf.o
      _main in bmon-bmon.o
  "_cfg_setstr", referenced from:
      _main in bmon-bmon.o
  "_cfg_size", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
      _add_div in bmon-conf.o
  "_cfg_title", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bmon] Error 1
make: *** [all-recursive] Error 1
 
### Detail of the first error:

/opt/src/bmon-3.6> search -cv “_cfg_free” .
./compiler-stderr.log:2:  "_cfg_free", referenced from:
./compiler-stderr.log:4:     (maybe you meant: _element_cfg_free)
./include/bmon/element_cfg.h:50:extern void   element_cfg_free(struct element_cfg *);
./src/element_cfg.c:62:static void __element_cfg_free(struct element_cfg *ec)
./src/element_cfg.c:71:void element_cfg_free(struct element_cfg *ec)
./src/element_cfg.c:76:	__element_cfg_free(ec);
./src/element_cfg.c:95:	__element_cfg_free(ec);
/opt/src/bmon-3.6>

**Comment by tgraf** [comment]
This looks like libconfuse is messing something up. bmon is not calling any of these functions directly. Can you send me the output of ```make V=1```?

**Comment by hdatma** [comment]
Making all in src
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-utils.o -MD -MP -MF .deps/bmon-utils.Tpo -c -o bmon-utils.o `test -f 'utils.c' || echo './'`utils.c
mv -f .deps/bmon-utils.Tpo .deps/bmon-utils.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-unit.o -MD -MP -MF .deps/bmon-unit.Tpo -c -o bmon-unit.o `test -f 'unit.c' || echo './'`unit.c
mv -f .deps/bmon-unit.Tpo .deps/bmon-unit.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-conf.o -MD -MP -MF .deps/bmon-conf.Tpo -c -o bmon-conf.o `test -f 'conf.c' || echo './'`conf.c
mv -f .deps/bmon-conf.Tpo .deps/bmon-conf.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-input.o -MD -MP -MF .deps/bmon-input.Tpo -c -o bmon-input.o `test -f 'input.c' || echo './'`input.c
mv -f .deps/bmon-input.Tpo .deps/bmon-input.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-output.o -MD -MP -MF .deps/bmon-output.Tpo -c -o bmon-output.o `test -f 'output.c' || echo './'`output.c
mv -f .deps/bmon-output.Tpo .deps/bmon-output.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-group.o -MD -MP -MF .deps/bmon-group.Tpo -c -o bmon-group.o `test -f 'group.c' || echo './'`group.c
mv -f .deps/bmon-group.Tpo .deps/bmon-group.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-element.o -MD -MP -MF .deps/bmon-element.Tpo -c -o bmon-element.o `test -f 'element.c' || echo './'`element.c
mv -f .deps/bmon-element.Tpo .deps/bmon-element.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-attr.o -MD -MP -MF .deps/bmon-attr.Tpo -c -o bmon-attr.o `test -f 'attr.c' || echo './'`attr.c
mv -f .deps/bmon-attr.Tpo .deps/bmon-attr.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-element_cfg.o -MD -MP -MF .deps/bmon-element_cfg.Tpo -c -o bmon-element_cfg.o `test -f 'element_cfg.c' || echo './'`element_cfg.c
mv -f .deps/bmon-element_cfg.Tpo .deps/bmon-element_cfg.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-history.o -MD -MP -MF .deps/bmon-history.Tpo -c -o bmon-history.o `test -f 'history.c' || echo './'`history.c
mv -f .deps/bmon-history.Tpo .deps/bmon-history.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-graph.o -MD -MP -MF .deps/bmon-graph.Tpo -c -o bmon-graph.o `test -f 'graph.c' || echo './'`graph.c
mv -f .deps/bmon-graph.Tpo .deps/bmon-graph.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-bmon.o -MD -MP -MF .deps/bmon-bmon.Tpo -c -o bmon-bmon.o `test -f 'bmon.c' || echo './'`bmon.c
mv -f .deps/bmon-bmon.Tpo .deps/bmon-bmon.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-module.o -MD -MP -MF .deps/bmon-module.Tpo -c -o bmon-module.o `test -f 'module.c' || echo './'`module.c
mv -f .deps/bmon-module.Tpo .deps/bmon-module.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-in_netlink.o -MD -MP -MF .deps/bmon-in_netlink.Tpo -c -o bmon-in_netlink.o `test -f 'in_netlink.c' || echo './'`in_netlink.c
mv -f .deps/bmon-in_netlink.Tpo .deps/bmon-in_netlink.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-in_null.o -MD -MP -MF .deps/bmon-in_null.Tpo -c -o bmon-in_null.o `test -f 'in_null.c' || echo './'`in_null.c
mv -f .deps/bmon-in_null.Tpo .deps/bmon-in_null.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-in_dummy.o -MD -MP -MF .deps/bmon-in_dummy.Tpo -c -o bmon-in_dummy.o `test -f 'in_dummy.c' || echo './'`in_dummy.c
mv -f .deps/bmon-in_dummy.Tpo .deps/bmon-in_dummy.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-in_proc.o -MD -MP -MF .deps/bmon-in_proc.Tpo -c -o bmon-in_proc.o `test -f 'in_proc.c' || echo './'`in_proc.c
mv -f .deps/bmon-in_proc.Tpo .deps/bmon-in_proc.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-in_sysctl.o -MD -MP -MF .deps/bmon-in_sysctl.Tpo -c -o bmon-in_sysctl.o `test -f 'in_sysctl.c' || echo './'`in_sysctl.c
mv -f .deps/bmon-in_sysctl.Tpo .deps/bmon-in_sysctl.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-out_null.o -MD -MP -MF .deps/bmon-out_null.Tpo -c -o bmon-out_null.o `test -f 'out_null.c' || echo './'`out_null.c
mv -f .deps/bmon-out_null.Tpo .deps/bmon-out_null.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-out_format.o -MD -MP -MF .deps/bmon-out_format.Tpo -c -o bmon-out_format.o `test -f 'out_format.c' || echo './'`out_format.c
mv -f .deps/bmon-out_format.Tpo .deps/bmon-out_format.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-out_ascii.o -MD -MP -MF .deps/bmon-out_ascii.Tpo -c -o bmon-out_ascii.o `test -f 'out_ascii.c' || echo './'`out_ascii.c
mv -f .deps/bmon-out_ascii.Tpo .deps/bmon-out_ascii.Po
/opt/llvm/bin/clang -DHAVE_CONFIG_H -I. -I../include/bmon   -I/opt/test/share/confuse/include -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2 -MT bmon-out_curses.o -MD -MP -MF .deps/bmon-out_curses.Tpo -c -o bmon-out_curses.o `test -f 'out_curses.c' || echo './'`out_curses.c
mv -f .deps/bmon-out_curses.Tpo .deps/bmon-out_curses.Po
/opt/llvm/bin/clang -I../include -I../include -DSYSCONFDIR=\"/opt/test/share/bmon/etc\" -D_GNU_SOURCE -Wall  -I/opt/test/share/confuse/include   -g -O2  -L/opt/test/share/confuse/lib -o bmon bmon-utils.o bmon-unit.o bmon-conf.o bmon-input.o bmon-output.o bmon-group.o bmon-element.o bmon-attr.o bmon-element_cfg.o bmon-history.o bmon-graph.o bmon-bmon.o bmon-module.o bmon-in_netlink.o bmon-in_null.o bmon-in_dummy.o bmon-in_proc.o bmon-in_sysctl.o bmon-out_null.o bmon-out_format.o bmon-out_ascii.o bmon-out_curses.o -lncurses -L/opt/test/share/confuse/lib   -lm 
Undefined symbols for architecture x86_64:
  "_cfg_free", referenced from:
      _conf_shutdown in bmon-conf.o
     (maybe you meant: _element_cfg_free)
  "_cfg_getbool", referenced from:
      _unit_divisor in bmon-unit.o
      _conf_init_post in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_getfloat", referenced from:
      _conf_init_post in bmon-conf.o
      _get_lifecycles in bmon-conf.o
      _configfile_read_history in bmon-conf.o
  "_cfg_getint", referenced from:
      _conf_init_post in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
      _main in bmon-bmon.o
  "_cfg_getnfloat", referenced from:
      _add_div in bmon-conf.o
  "_cfg_getnsec", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_getnstr", referenced from:
      _add_div in bmon-conf.o
  "_cfg_getstr", referenced from:
      _conf_init_post in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
  "_cfg_init", referenced from:
      ___conf_init in bmon-conf.o
  "_cfg_parse", referenced from:
      _conf_read in bmon-conf.o
  "_cfg_parse_buf", referenced from:
      _conf_init_pre in bmon-conf.o
  "_cfg_setbool", referenced from:
      _main in bmon-bmon.o
  "_cfg_setfloat", referenced from:
      _main in bmon-bmon.o
  "_cfg_setint", referenced from:
      _set_unit_exp in bmon-conf.o
      _main in bmon-bmon.o
  "_cfg_setstr", referenced from:
      _main in bmon-bmon.o
  "_cfg_size", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
      _add_div in bmon-conf.o
  "_cfg_title", referenced from:
      _configfile_read_units in bmon-conf.o
      _configfile_read_history in bmon-conf.o
      _configfile_read_attrs in bmon-conf.o
      _configfile_read_element_cfg in bmon-conf.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bmon] Error 1
make: *** [all-recursive] Error 1

**Comment by tgraf** [comment]
The linker is missing a ```-lconfuse``` which leads to the unresolved symbols.

Can you run:
```grep CONFUSE_LIBS Makefile* config.*```
so we can see if configure is setting the CONFUSE_LIBS variable correctly?

**Comment by hdatma** [comment]
> grep CONFUSE_LIBS Makefile* config.*
Makefile:CONFUSE_LIBS = -L/opt/test/share/confuse/lib
Makefile.in:CONFUSE_LIBS = @CONFUSE_LIBS@
config.log:ac_cv_env_CONFUSE_LIBS_set=set
config.log:ac_cv_env_CONFUSE_LIBS_value=-L/opt/test/share/confuse/lib
config.log:pkg_cv_CONFUSE_LIBS=-L/opt/test/share/confuse/lib
config.log:CONFUSE_LIBS='-L/opt/test/share/confuse/lib'
config.status:ac_cs_config="'--prefix=/opt/test/share/bmon' '--mandir=/opt/test/share/man' '--enable-dependency-tracking' 'CC=/opt/llvm/bin/clang' 'LDFLAGS=-L/opt/test/share/confuse/lib' 'CPPFLAGS=-I/opt/test/share/confuse/include' 'CONFUSE_CFLAGS=-I/opt/test/share/confuse/include' 'CONFUSE_LIBS=-L/opt/test/share/confuse/lib'"
config.status:  set X /bin/sh './configure'  '--prefix=/opt/test/share/bmon' '--mandir=/opt/test/share/man' '--enable-dependency-tracking' 'CC=/opt/llvm/bin/clang' 'LDFLAGS=-L/opt/test/share/confuse/lib' 'CPPFLAGS=-I/opt/test/share/confuse/include' 'CONFUSE_CFLAGS=-I/opt/test/share/confuse/include' 'CONFUSE_LIBS=-L/opt/test/share/confuse/lib' $ac_configure_extra_args --no-create --no-recursion
config.status:S["CONFUSE_LIBS"]="-L/opt/test/share/confuse/lib"

**Comment by hdatma** [comment]
>ls -l /opt/test/share/confuse/lib/

total 264
-rw-r--r--  1 root  wheel  129720 Jun 24 09:08 libconfuse.a
-rwxr-xr-x  1 root  wheel     905 Jun 24 09:08 libconfuse.la
drwxr-xr-x  3 root  wheel     102 Jun 24 09:08 pkgconfig

**Comment by tgraf** [comment]
CONFUSE_LIBS is missing a -lconfuse

Check pkg-config output:
```
$ pkg-config --libs libconfuse
-lconfuse 
```

You can fix this by compiling with:

make LDFLAGS=-lconfuse

**Comment by tgraf** [comment]
Closing this since it's not a problem of bmon itself.

**Comment by hdatma** [comment]
Thank you.
