### ISSUE TITLE
bmonrc policy order

### ISSUE THREAD

**Issue by broomdodger** [tgraf/bmon#34]
In the .bmonrc I added:
```
policy='wlp3s0,enp2s0'
```
In the hope that the wireless interface would be the first in the list. But it seems the order is alphabetical.

Would it be possible to have the interface selector list by the order in `policy` ?

**Comment by tgraf** [comment]
That thought never occur to me but it does make sense. The order is equivalent to the order the interfaces are returned by the kernel. There is no sorting enforcement right now.

**Comment by broomdodger** [comment]
Rather than change the **order** of interfaces...
Can the interface **pointer** be set by the bmonrc file?
When bmon starts, it would be nice to specify the interface, list order is not important.

**Comment by tgraf** [comment]
@broomdodger I've added this capability in commit ddcd5e7d24ad57257117402529eacddd8feed2cf. Let me know if that suits your need.

**Comment by broomdodger** [comment]
Thank you, it seems to work changing policy in the .bmonrc.
Attached are two screenshots, one wire, one wifi.
Changing the .bmonrc and yes! the first in list is selected.

Selecting 'd' there is ui cosmetic issue.
The screen size does not matter there is still white in the 'd' area.
Is that fixable?
![20160802 212057](https://cloud.githubusercontent.com/assets/2816723/17353802/06971e42-58f8-11e6-96e8-7ebe80f5aaf4.jpg)
![20160802 212344](https://cloud.githubusercontent.com/assets/2816723/17353801/0696a0d4-58f8-11e6-9eea-9aedd43431b4.jpg)

**Comment by blastmaster** [comment]
Yes, I think this is fixable. This is also already known in #43 . I think at least next week i will have time to work on these cosmetic problem. Sorry.

**Comment by tgraf** [comment]
I'm closing this as the other issue is tracked in #43

**Comment by broomdodger** [comment]
> I think at least next week i will have time to work on these cosmetic problem.

I downloaded a recent **master.zip**, compiled and no more cosmetic problem.
Thank you.
Bill
