### ISSUE TITLE
Automatically open detailed lists?

### ISSUE THREAD

**Issue by Berzerker** [tgraf/bmon#35]
Is there a way to have bmon automatically open the detailed lists instead of hitting "d" and "i"?

**Comment by tgraf** [comment]
Yes, start bmon with the details options `bmon -o curses:details`. See `bmon -o curses:help` for additional help when using the curses module.

**Comment by Berzerker** [comment]
So, this only opens the details section, "d", but is there a way to have it open "d" and "i" as well?

**Comment by tgraf** [comment]
Not yet. Trivial to add though.

**Comment by tgraf** [comment]
Added in commit f78c0e5b98a45dcd142e4b7bef1d42cb23064239
