### ISSUE TITLE
"detailed statistics" does not color its whole area

### ISSUE THREAD

**Issue by ammongit** [tgraf/bmon#43]
On my terminal emulator, I have set the default background color and black color to be different. The "detailed statistics" does not black out the entirety of its area, as seen in these pictures:
![curses](https://cloud.githubusercontent.com/assets/8848022/17281777/541dd77e-5753-11e6-8553-ec6897c7852f.png)
![curses3](https://cloud.githubusercontent.com/assets/8848022/17281782/587aca7a-5753-11e6-8c29-9f3053b22233.png)
![curses2](https://cloud.githubusercontent.com/assets/8848022/17281779/56ffc1dc-5753-11e6-86b4-bd55ddf0e8d3.png)

It's pretty reproducible, no matter how many times you enable/disable `d` and `i` you still get that particular area of the screen not blacked out.

**Comment by blastmaster** [comment]
Ohh, thats not pretty. I will look if I can fix this.

**Comment by ammongit** [comment]
That screenshot is for Terminator 0.98. I reproduced the same behavior on iTerm2 3.0.5:

![screen shot 2016-08-01 at 10 14 34 am](https://cloud.githubusercontent.com/assets/8848022/17302444/24f33948-57d1-11e6-9afa-84bb16466fbd.png)

**Comment by tgraf** [comment]
Fixed in 702df3c0a1e3346fdb80dd6e5a2ec263816f9784
