### ISSUE TITLE
3.7.x series in Fedora current and future?

### ISSUE THREAD

**Issue by nrvale0** [tgraf/bmon#56]
Just switched over to Fedora 25 from Ubuntu 16.10 and noticed that the version of bmon in current and future Fedora is 3.7.x series. Was hoping to get back to >= 3.9.x in order to pull in color support.

Is 3.7 considered the more stable release and thus the inclusion in Fedora? Some reason why I might *not* consider rolling a custom Fedora RPM for >= 3.9.x?

Thx for the very nifty tool, btw. Very useful.

**Comment by tgraf** [comment]
3.9.x is perfectly stable. I just haven't gotten around to doing a 3.9.x build for Fedora.

**Comment by nrvale0** [comment]
If I get around to compiling a custom RPM with latest version I will share work. Thx again.

**Comment by nrvale0** [comment]
I @tgraf I have a bmon.spec which I've used to compile 4.x for Fedora 25. I don't see the spec in the repo or I would send in a PR. Advice? @tgraf

**Comment by nrvale0** [comment]
Close in favor of #60.
